# Generated by Django 3.0 on 2019-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divorces2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('divorces_2018', models.FloatField(blank=True, db_column='Divorces_2018', null=True)),
            ],
            options={
                'db_table': 'divorces_2018',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MortalityBeforeSixty2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('mortality_before_sixty_2018', models.FloatField(blank=True, db_column='Mortality_before_sixty_2018', null=True)),
            ],
            options={
                'db_table': 'mortality_before_sixty_2018',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salaries2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('salary_2018', models.FloatField(blank=True, db_column='Salary_2018', null=True)),
            ],
            options={
                'db_table': 'salaries_2018',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnemploymentRate2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('unemployment_rate_2018', models.FloatField(blank=True, db_column='Unemployment_rate_2018', null=True)),
            ],
            options={
                'db_table': 'unemployment_rate_2018',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ListBoard',
        ),
    ]
